repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/pre-commit/mirrors-mypy
    # We can't use the latest version due to a regression in mypy 1.7.0
    # See https://github.com/python/mypy/issues/17191 for more information
    rev: v1.6.1
    hooks:
    - id: mypy
      exclude: "docs/"
      additional_dependencies: [pytest, typing-extensions]
      types: [python]
-   repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.396
    hooks:
    - id: pyright
      additional_dependencies: [pytest, typing-extensions, aioconsole]
      types: [python]
-   repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.11.7
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format
